config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :tabular_data
  resources :daily_opportunity_stats, only: :index

  resources :blank_turbo_frames, only: :show
  resources :companies

  resource :dashboard, only: :show

  resources :documents

  resources :moves do
    resources :metrics
    resources :notes
    resources :opportunity_metrics
  end

  resources :notes

  resources :opportunities do
    resources :notes
    resources :tasks
  end

  resources :tasks do
    resources :notes
  end

  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "dashboards#show"
end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id         :bigint           not null, primary key
#  name       :string
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Quote < ApplicationRecord
  acts_as_list

  validates :name, presence: true

  broadcasts_to ->(quote) { "quotes" }, inserts_by: :append
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
        format.turbo_stream
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy!

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_quote
    @quote = Quote.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def quote_params
    params.fetch(:quote, {}).permit(:name, :position)
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.haml
= simple_form_for quote do |form|
  = render Common::Form::ErrorsComponent.new(form: form)
  
  .flex
    .grow.mr-2
      = form.input :name, label: false, input_html: { autofocus: true }
      = form.input :position

    .save.mr-2
      = render(Primer::Beta::Button.new(scheme: :primary, type: :submit)) { "Save"}

    .cancel
      = link_to quote do
        = render(Primer::Beta::Button.new(scheme: :primary, type: :button)) { "Cancel"}

app/views/quotes/_quote.html.haml
%turbo-stream{ action: :prepend, target: :quotes }
  %template
    = turbo_frame_tag(quote, data: { sortable_update_url: quote_path(quote, format: :json) } ) do
      %div.card.mt-4.quote{ data: { auto_sortable_target: :position, sortable_position: quote.position }}
        = link_to quote.name, [quote], data: { turbo_frame: :_top }

        = button_to "Delete", quote_path(quote), method: :delete, class: "inline"
        = render(Primer::Beta::Link.new(href: url_for([:edit, quote]))) { "Edit"}

app/views/quotes/create.turbo_stream.haml
= turbo_stream.prepend "quotes", @quote
= turbo_stream.update Quote.new, ""

app/views/quotes/destroy.turbo_stream.haml
= turbo_stream.remove @quote

app/views/quotes/edit.html.haml
%main.container
  = link_to sanitize("&larr; Back to quote"), quote_path(@quote)
  .header
    %h1 Edit quote
  = turbo_frame_tag @quote do
    %div.card.mt-4.quote
      = render "form", quote: @quote

app/views/quotes/index.html.haml
= turbo_stream_from "quotes"

%main.container
  %turbo-frame#header
    .header
      %h1 Quotes
    = link_to "New quote", [:new, :quote], data: { turbo_frame: dom_id(Quote.new) }

  = turbo_frame_tag dom_id(Quote.new)

  %turbo-frame#quotes{ data: { controller: "auto-sortable", auto_sortable_target: :frame } }
    .sortable{ data: { controller: :sortable, sortable_response_kind_value: :json, sortable_resource_name_value: :quote, sortable_param_name_value: :position} }
      = render @quotes

app/views/quotes/new.html.haml
%main.container
  = link_to "Back to quotes", [:quotes], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  .header
    %h1 New Quote
  
  = turbo_frame_tag @quote do
    %div.card.mt-4.quote
      = render "form", quote: @quote

app/views/quotes/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
  = turbo_frame_tag @quote do
    %div.card.mt-4.quote
      = render @quote
    = link_to "Edit this quote", edit_quote_path(@quote), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to "Destroy this quote", quote_path(@quote), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to "Back to quotes", quotes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/quotes/update.turbo_stream.haml
= turbo_stream.update @quote