config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :tabular_data
  resources :daily_opportunity_stats, only: :index

  resources :blank_turbo_frames, only: :show
  resources :companies

  resource :dashboard, only: :show

  resources :documents

  resources :moves do
    resources :metrics
    resources :notes
    resources :opportunity_metrics
  end

  resources :notes

  resources :opportunities do
    resources :notes
    resources :tasks
  end

  resources :tasks do
    resources :notes
  end

  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "dashboards#show"
end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id         :bigint           not null, primary key
#  data       :jsonb
#  file       :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_documents_on_user_id  (user_id)
#
class Document < ApplicationRecord
  has_one_attached :file
  belongs_to :user

  validates :name, :file, presence: true

  has_rich_text :description
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[show edit update destroy]
  before_action :build_document, only: %i[new create]

  # GET /documents or /documents.json
  def index
    @documents = Current.user.documents
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy!

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def build_document
    @document = Document.new(document_params.merge(user: Current.user))
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def document_params
    params[:document].present? ? params.require(:document).permit(:name, :description, :file) : {}
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.haml
%div{:id => "#{dom_id document}"}
  = document.name
  = document.description.to_s
  = document.file

  - if action_name != "show"
    = link_to "Show this document", document, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to "Edit this document", edit_document_path(document), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/documents/_form.html.haml
= simple_form_for document do |form|
  = render Common::Form::ErrorsComponent.new(form: form)

  = form.input :name
  = form.input :description, as: :rich_text_area
  = form.input :file, input_html: { accept: 'application/pdf' }
  
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/documents/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing document
  = render "form", document: @document
  = link_to "Show this document", @document, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to documents", documents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/documents/index.html.haml
.w-full
  .flex.justify-between.items-center
    %h1.font-bold.text-4xl Documents
    = link_to "New document", new_document_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #documents.min-w-full
    = render @documents

app/views/documents/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl New document
  = render "form", document: @document
  = link_to "Back to documents", documents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/documents/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
    = render @document
    = link_to "Edit this document", edit_document_path(@document), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = render Common::Element::DestroyLinkComponent.new(model: @document, text: "Destroy")
    = link_to "Back to documents", documents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"