config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :tabular_data
  resources :daily_opportunity_stats, only: :index

  resources :blank_turbo_frames, only: :show
  resources :companies

  resource :dashboard, only: :show

  resources :documents

  resources :moves do
    resources :metrics
    resources :notes
    resources :opportunity_metrics
  end

  resources :notes

  resources :opportunities do
    resources :notes
    resources :tasks
  end

  resources :tasks do
    resources :notes
  end

  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "dashboards#show"
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id                :bigint           not null, primary key
#  name              :string
#  opportunity_count :integer
#  timestamps        :string
#  uri               :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  user_id           :bigint
#
# Indexes
#
#  index_companies_on_user_id  (user_id)
#
class Company < ApplicationRecord
  include PgSearch::Model
  has_paper_trail

  has_many :opportunities
  belongs_to :user

  validates :name, presence: true
  validates :uri, url: {allow_nil: true, allow_blank: true}

  scope :alphabetical, -> { order(name: :asc) }

  pg_search_scope :global_search,
    against: [:name],
    using: {
      tsearch: {prefix: true}
    }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]
  before_action :build_company, only: %i[new create]
  before_action :build_companies, only: :index

  breadcrumb "Companies", [:companies], match: :exact

  # GET /companies or /companies.json
  def index
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    respond_to do |format|
      if @company.save
        build_companies
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy!

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private

  def build_companies
    @companies = Current.user.companies.distinct.alphabetical
  end

  def build_company
    @company = Company.new(company_params.merge(user: Current.user))
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def company_params
    params.fetch(:company, {}).permit!
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.haml
%turbo-frame{ id: dom_id(company) }
  %div{id: dom_id(company)}
    = link_to company do
      = highlight company.name, params[:search]
      - if company.uri.present?
        %span
          = link_to company.uri, target: :_blank do
            = heroicon "arrow-top-right-on-square", size: 16, class: "pb-0.5 inline"

    = link_to [:edit, company] do
      = heroicon "cog-6-tooth", size: 16, class: "pb-0.5 inline"
    - if company.opportunities.none?
      = render Common::Element::DestroyLinkComponent.new(model: company, text: heroicon("trash", size: 16, class: "pb-0.5 inline"), args: { class: "inline" } )
    %span.text-xs
      = link_to [:opportunities, search: company.name], data: { turbo_frame: :_top } do
        (#{company.opportunity_count.to_i} opportunities)

app/views/companies/_form.html.haml
%turbo-frame{ id: dom_id(company) }
  = simple_form_for company do |form|
    = render Common::Form::ErrorsComponent.new(form: form)
    = form.input :name
    = form.input :uri
    .flex.mt-4
      .show.grow
        = link_to [company] do
          = render(Primer::Beta::Button.new(scheme: :primary, type: :button)) { "Cancel"}
      .save
        = render(Primer::Beta::Button.new(scheme: :primary, type: :submit)) { "Save"}

app/views/companies/_list.html.haml
#companies.grid.grid-cols-2.gap-2
  - @companies.each do |company|
    = render company
  

app/views/companies/create.turbo_stream.haml
= turbo_stream.update "companies", partial: "companies/list"
= turbo_stream.update Company.new, ""

app/views/companies/destroy.turbo_stream.haml
= turbo_stream.remove dom_id(@company)

app/views/companies/edit.html.haml
= render "form", company: @company

app/views/companies/index.html.haml
%p{:style => "color: green"}= notice
.flex.mb-2
  %h1.grow Companies
  .new
    = link_to [:new, :company], data: { turbo_frame: dom_id(Company.new) } do
      = render(Primer::Beta::Button.new(scheme: :primary, type: :button)) { "New"}

%turbo-frame{ id: dom_id(Company.new) }

%turbo-frame#companies
  = render "list"

app/views/companies/new.html.haml
%h1 New company
= render "form", company: @company
%br/
%div
  = link_to "Back to companies", companies_path

app/views/companies/show.html.haml
%p{:style => "color: green"}= notice
= render @company
%div
  = link_to "Edit this company", edit_company_path(@company)
  |
  \#{link_to "Back to companies", companies_path}