config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :tabular_data
  resources :daily_opportunity_stats, only: :index

  resources :blank_turbo_frames, only: :show
  resources :companies

  resource :dashboard, only: :show

  resources :documents

  resources :moves do
    resources :metrics
    resources :notes
    resources :opportunity_metrics
  end

  resources :notes

  resources :opportunities do
    resources :notes
    resources :tasks
  end

  resources :tasks do
    resources :notes
  end

  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "dashboards#show"
end

app/models/opportunity_metric.rb
# == Schema Information
#
# Table name: opportunity_metrics
#
#  id             :bigint           not null, primary key
#  data           :jsonb
#  score          :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  metric_id      :bigint
#  opportunity_id :bigint
#
# Indexes
#
#  index_opportunity_metrics_on_metric_id                     (metric_id)
#  index_opportunity_metrics_on_opportunity_id                (opportunity_id)
#  index_opportunity_metrics_on_opportunity_id_and_metric_id  (opportunity_id,metric_id) UNIQUE
#
class OpportunityMetric < ApplicationRecord
  belongs_to :metric
  belongs_to :opportunity

  after_commit :update_opportunity_total_score

  validates :metric_id, uniqueness: { scope: :opportunity_id,
    message: "and opportunity must be unique" }


  def update_opportunity_total_score
    return unless self.previous_changes["score"].present?

    opportunity.calculate_score!
    opportunity.calculate_opportunity_ranking
  end

  def calculated_score
    (score.to_i * metric.weight.to_i)
  end
end

app/controllers/opportunity_metrics_controller.rb
class OpportunityMetricsController < ApplicationController
  before_action :set_opportunity_metric, only: %i[ show edit update destroy ]
  before_action :find_move, only: [:index]
  before_action :build_breadcrumbs

  # GET /opportunity_metrics or /opportunity_metrics.json
  def index
    @opportunities = @move.opportunities.metrics_enabled.order(ranking: :asc)
  end

  # GET /opportunity_metrics/1 or /opportunity_metrics/1.json
  def show
  end

  # GET /opportunity_metrics/new
  def new
    @opportunity_metric = OpportunityMetric.new
  end

  # GET /opportunity_metrics/1/edit
  def edit
  end

  # POST /opportunity_metrics or /opportunity_metrics.json
  def create
    @opportunity_metric = OpportunityMetric.new(opportunity_metric_params)

    respond_to do |format|
      if @opportunity_metric.save
        format.html { redirect_to opportunity_metric_url(@opportunity_metric), notice: "Opportunity metric was successfully created." }
        format.json { render :show, status: :created, location: @opportunity_metric }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @opportunity_metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opportunity_metrics/1 or /opportunity_metrics/1.json
  def update
    respond_to do |format|
      if @opportunity_metric.update(opportunity_metric_params)
        format.html { redirect_to opportunity_metric_url(@opportunity_metric), notice: "Opportunity metric was successfully updated." }
        format.json { render :show, status: :ok, location: @opportunity_metric }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @opportunity_metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opportunity_metrics/1 or /opportunity_metrics/1.json
  def destroy
    @opportunity_metric.destroy!

    respond_to do |format|
      format.html { redirect_to opportunity_metrics_url, notice: "Opportunity metric was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def build_breadcrumbs 
      breadcrumb "Moves", [:moves], match: :exact
      breadcrumb @move.name, [@move], match: :exact
      breadcrumb "Opportunity Metrics", [@move, :opportunity_metrics], match: :exact
    end

    def find_move
      @move = Move.find(params[:move_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_opportunity_metric
      @opportunity_metric = OpportunityMetric.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def opportunity_metric_params
      params.fetch(:opportunity_metric, {})
    end
end

app/helpers/opportunity_metrics_helper.rb
module OpportunityMetricsHelper
end

app/views/opportunity_metrics/_form.html.haml
= form_with(model: opportunity_metric, class: "contents") do |form|
  = render Common::Form::ErrorsComponent.new(form: form)

  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/opportunity_metrics/_list.html.haml
.relative.overflow-x-auto
  %table{ class: "w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400" }
    %thead{ class: "text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400" }
      %tr
        %th{ scope: "col", class: "px-6 py-3" } 
          Rank
        %th{ scope: "col", class: "px-6 py-3" } 
          Total Score
        %th{ scope: "col", class: "px-6 py-3" }
          Opportunity
        - @move.metrics.each do |metric|
          %th{ scope: "col", class: "px-6 py-3" }
            = metric.name
    %tbody
      - opportunities.each do |opportunity|
        = render "show", opportunity: opportunity

app/views/opportunity_metrics/_opportunity_metric.html.haml
%div{:id => "#{dom_id opportunity_metric}"}
  - if action_name != "show"
    = link_to "Show this opportunity metric", opportunity_metric, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to "Edit this opportunity metric", edit_opportunity_metric_path(opportunity_metric), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/opportunity_metrics/_show.html.haml
%tr{ class: "g-white border-b dark:bg-gray-800 dark:border-gray-700" }
  %th{ scope: "row", class: "px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"}
    = opportunity.ranking
  %td{ class: "text-center" }
    = opportunity.total_score
  %th{ scope: "row", class: "px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"}
    = link_to opportunity, opportunity
    %br
    = opportunity.company.name
  - opportunity.opportunity_metrics.each do |opportunity_metric|
    %td{ class: "text-center" }
      = opportunity_metric.calculated_score

app/views/opportunity_metrics/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing opportunity metric
  = render "form", opportunity_metric: @opportunity_metric
  = link_to "Show this opportunity metric", @opportunity_metric, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to opportunity metrics", opportunity_metrics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/opportunity_metrics/index.html.haml
.w-full
  = render(Primer::Beta::Heading.new(tag: :h1)) { "Opportunity Metrics" }
  #opportunity_metrics.min-w-full
    = render "list", opportunities: @opportunities

app/views/opportunity_metrics/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl New opportunity metric
  = render "form", opportunity_metric: @opportunity_metric
  = link_to "Back to opportunity metrics", opportunity_metrics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/opportunity_metrics/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  asdfasdf
  = opportunity